### ISSUE TITLE
[Bug] Able to post comment after logout

### ISSUE THREAD

**Issue by RychardHunt** [merta1/CSE442_Project#109]
I was able to post comments as my account, demo and then after I logout, I was still able to post comments as my account, demo.

![Screen Shot 2019-04-16 at 8 25 58 PM](https://user-images.githubusercontent.com/22261791/56252487-fe9b0580-6085-11e9-81ca-15d86045a30e.jpg)

**Comment by dadkins20** [comment]
This is fixed in our latest build for Sprint 3.
