### ISSUE TITLE
[Bug] Loading Buffer

### ISSUE THREAD

**Issue by Stevenn-Li** [merta1/CSE442_Project#110]
After logging in, loading buffers forever. This is also triggered after registration. 
<img width="1147" alt="Screen Shot 2019-04-16 at 11 10 13 PM" src="https://user-images.githubusercontent.com/41338771/56258267-eaaece00-609c-11e9-8f14-f85955c58d67.png">

**Comment by dadkins20** [comment]
This issue is fixed in the latest build for Sprint 3.
