### ISSUE TITLE
[Bug] Several bugs

### ISSUE THREAD

**Issue by Zhenduo** [merta1/CSE442_Project#111]
#16 – The comment works well, but when I type in a comment box, the text shows on both comment boxes.

#94 – Acceptance test passed.

#17 – After I register for an account, the page is keep loading until I refresh the page. I believe the account is registered because I can login after I refresh the page, but after clicking the register button, the page is endlessly loading. In addition, after I login, the page is still loading instead of taking me to the debate list unless I refresh the page.
 
#20 – I haven’t login yet, but I can join the debates.

#47 – Acceptance test passed.

**Comment by dadkins20** [comment]
This issue was fixed in the latest build for Sprint 3.
